repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --profile black .
        language: python
        types: [python]
      - id: black
        name: black
        entry: poetry run  black . --check --preview
        language: python
        types: [python]
      - id: linter
        name: Linter (pylint)
        entry: poetry run pylint
        language: system
        types: [python]
        stages: [commit]
      - id: typing
        name: Type checker (mypy)
        entry: poetry run mypy
        args:
          [
            --ignore-missing-imports,
            --no-implicit-optional,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
          ]
        language: system
        types: [python]
        stages: [commit]
